Traceback (most recent call last):
  File "/home/sc.uni-leipzig.de/jw54kysa/FedDaisy/CIFAR10/feddc_CIFAR10_pytorch.py", line 128, in <module>
    os.mkdir(exp_path)
FileExistsError: [Errno 17] File exists: 'FedDC_cifar10_nc150cl_n64_b64_d1_a10_lr0_scheduleNone_r1000_s1_2024-12-03_22-29-54'
Traceback (most recent call last):
  File "/home/sc.uni-leipzig.de/jw54kysa/FedDaisy/CIFAR10/feddc_CIFAR10_pytorch.py", line 128, in <module>
Traceback (most recent call last):
  File "/home/sc.uni-leipzig.de/jw54kysa/FedDaisy/CIFAR10/feddc_CIFAR10_pytorch.py", line 128, in <module>
    os.mkdir(exp_path)
FileExistsError: [Errno 17] File exists: 'FedDC_cifar10_nc150cl_n64_b64_d1_a10_lr0_scheduleNone_r1000_s1_2024-12-03_22-29-54'
    os.mkdir(exp_path)
FileExistsError: [Errno 17] File exists: 'FedDC_cifar10_nc150cl_n64_b64_d1_a10_lr0_scheduleNone_r1000_s1_2024-12-03_22-29-54'
srun: error: paula05: tasks 0-2: Exited with exit code 1
/home/sc.uni-leipzig.de/jw54kysa/FedDaisy/CIFAR10/dataset_cifar10.py:30: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:78.)
  X_train = torch.cuda.FloatTensor(X_train).permute(0,3,1,2)
